[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude =  '''
/(
    \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.vscode
    | \.vercel
    | __pycache__
    | _build
    | migrations
    | buck-out
    | build
    | dist
    | .venv
)/
'''
